---
- name: Ensure application is deployed
  hosts: build

  become: true
  vars_files:
    - "files/secrets/devops.yml"

  tasks:
    - block:
        - name: Check that you can connect to webpage
          uri:
            url: http://{{ ip_addr_prod }}:{{ port_app }}
          retries: 5
          delay: 30

        - name: Check webservice application preProduction
          uri:
            url: http://{{ ip_addr_prod }}:{{ port_app }}/health
            method: GET
          retries: 8
          delay: 40
      tags:
        - build

    
